### PR TITLE
Django 2.x compatibility

### PR DESCRIPTION
**Pull request by ofalk**
Only a few small changes in order to work with Django 2.x.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @ofalk! I've created [OSPR-2386](https://openedx.atlassian.net/browse/OSPR-2386) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/django-openid-auth/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by mduboseedx** [comment]
@ofalk Could you please send in the signed Contributor agreement when you have a chance? You only need to do that once and we can review all your changes going forward. Thanks!

**Comment by ofalk** [comment]
@mduboseedx Sorry for the delay. Obviously I missed to sign and send the CA.
I've done so yesterday!

**Comment by mduboseedx** [comment]
jenkins ok to test

**Comment by mduboseedx** [comment]
@ofalk Thanks for sending the agreement!

@edx/platform-team Could you give this a review?

**Comment by doctoryes** [comment]
Looks good! But a couple of things are still needed:
- A rebase to resolve the conflict.
- Tests should pass. The easiest way will be to remove the Django 1.8/1.9/1.10 testing altogether, since we no longer support those Django versions.

**Comment by doctoryes** [comment]
And - thanks, @ofalk , for your contribution!

**Comment by edx-webhook** [comment]
@ofalk Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/django-openid-auth&entry.867055334=https://github.com/edx/django-openid-auth/pull/13&entry.1484655318=https://github.com/ofalk&entry.752974735=2018-05-03+10:24&entry.1917517419=2018-06-28+06:44&entry.2133058324=No) so we can improve your experience in the future.

**Comment by ofalk** [comment]
@doctoryes Seems @strycore PR #14 was faster. So, this is now autoclosed.

**Comment by doctoryes** [comment]
Ah - thanks anyway, @ofalk . Looking forward to your next PR! 😄

**Pull request closed without merging**
